### ISSUE TITLE
package.json: main file link is invalid

### ISSUE THREAD

**Issue by ducin** [apiaryio/fury-adapter-apib-serializer#4]
The [package.json](https://github.com/apiaryio/fury-adapter-apib-serializer/blob/master/package.json#L5) file says, that the main file is "`./lib/adapter.js`". And, as far as I can see, the actual file is ["`./src/adapter.js`"](https://github.com/apiaryio/fury-adapter-apib-serializer/blob/master/src/adapter.js). So either of them shall be renamed, because of the inconsistency.

**Comment by pksunkara** [comment]
This is an es6 repo which uses babel to generate `lib` folder.
